import Link from "next/link";
export default function HomePage() {
  const featureCards = [
    { title: "Verified Competitive Queues", desc: "Solo, duo, stack, and scrim matchmaking built around verified sessions, trust scoring, and fair entry requirements.", accent: "from-blue-600/25 to-blue-400/5" },
    { title: "Aggressive Anti-Cheat Enforcement", desc: "Live session gating, suspicious signal review, shadow queue controls, and transparent enforcement workflows.", accent: "from-red-600/25 to-red-400/5" },
    { title: "Tournament-Ready Platform", desc: "Brackets, roster management, event check-in, match control, and admin tooling for real competitive operations.", accent: "from-white/20 to-white/5" }
  ];
  const ladderRows = [
    { place: "#1", team: "Vanta Five", elo: "2486", record: "22-4" },
    { place: "#2", team: "HexCore", elo: "2432", record: "20-5" },
    { place: "#3", team: "Northside", elo: "2381", record: "19-7" }
  ];
  const tournaments = [
    { title: "Weekend Open Cup", detail: "64 teams • $2,500 prize pool", status: "Check-in Live" },
    { title: "Regional Qualifier", detail: "128 teams • LAN spot on the line", status: "Registration Open" },
    { title: "Challenger Series", detail: "16 teams • Invite level competition", status: "Bracket Locked" }
  ];
  const pricing = [
    { name: "Free", price: "$0", features: ["Verified queue access", "Basic match history", "Starter profile", "Appeals access"], featured: false },
    { name: "Pro", price: "$12/mo", features: ["Advanced stats", "Demo vault", "Priority support", "Team LFT tools"], featured: true },
    { name: "Organizer", price: "$79/mo", features: ["Brackets and seeding", "Event admin tools", "Branding controls", "Enhanced review workflow"], featured: false }
  ];
  return (
    <main className="min-h-screen bg-slate-950 text-white">
      <header className="sticky top-0 z-20 border-b border-white/10 bg-slate-950/85 backdrop-blur">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4 lg:px-10">
          <div><div className="text-2xl font-black uppercase tracking-wide">GamersOnline</div><div className="text-xs uppercase tracking-[0.22em] text-slate-400">GamersOnline.gg</div></div>
          <nav className="hidden gap-6 text-sm font-semibold text-slate-200 md:flex"><a href="#features">Features</a><a href="#anti-cheat">Anti-Cheat</a><a href="#ladders">Ladders</a><a href="#pricing">Pricing</a></nav>
          <div className="flex gap-3"><Link href="/login" className="rounded-xl border border-white/15 px-4 py-2 text-sm font-bold uppercase tracking-wide text-white">Log In</Link><Link href="/signup" className="rounded-xl bg-brandBlue px-4 py-2 text-sm font-bold uppercase tracking-wide text-white">Play Ranked</Link></div>
        </div>
      </header>
      <section className="relative overflow-hidden border-b border-white/10 px-6 py-16 lg:px-10 lg:py-20">
        <div className="absolute inset-0 bg-[linear-gradient(135deg,rgba(11,60,145,0.28),rgba(2,6,23,0.96)_40%,rgba(230,57,70,0.22))]" />
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(59,130,246,0.20),transparent_25%),radial-gradient(circle_at_bottom_right,rgba(239,68,68,0.20),transparent_22%)]" />
        <div className="relative mx-auto max-w-7xl">
          <div className="grid items-center gap-10 lg:grid-cols-[1.05fr,0.95fr]">
            <div>
              <div className="inline-flex items-center gap-2 rounded-full border border-red-400/20 bg-red-500/10 px-4 py-2 text-sm font-medium text-red-200"><span className="h-2.5 w-2.5 rounded-full bg-red-500" />Active Anti-Cheat Competitive Network</div>
              <h1 className="mt-6 max-w-4xl text-5xl font-black uppercase tracking-tight sm:text-6xl lg:text-7xl">Compete. Climb. <span className="text-red-500">Stay Clean.</span></h1>
              <p className="mt-6 max-w-2xl text-lg leading-8 text-slate-200">GamersOnline.gg is the next-generation CS2 competitive platform built for serious players, verified matchmaking, and aggressive anti-cheat enforcement.</p>
              <div className="mt-8 flex flex-wrap gap-4"><Link href="/signup" className="rounded-2xl bg-brandBlue px-6 py-3 text-sm font-bold uppercase tracking-wide text-white shadow-lg shadow-blue-950/40 transition hover:scale-[1.02] hover:bg-blue-700">Play Ranked</Link><Link href="/dashboard" className="rounded-2xl border border-white/15 bg-white/5 px-6 py-3 text-sm font-bold uppercase tracking-wide text-white transition hover:bg-white/10">View Leaderboards</Link></div>
              <div className="mt-10 grid max-w-2xl gap-4 sm:grid-cols-3">{[["Verified Players","128,420"],["Daily Matches","9,340"],["Flags Reviewed","31,882"]].map(([label,value]) => <div key={label} className="rounded-[24px] border border-white/10 bg-slate-950/70 p-4 backdrop-blur"><div className="text-3xl font-black">{value}</div><div className="mt-1 text-xs uppercase tracking-[0.18em] text-slate-400">{label}</div></div>)}</div>
            </div>
            <div className="relative"><div className="absolute -left-8 top-8 h-28 w-28 rounded-full bg-blue-600/20 blur-3xl" /><div className="absolute -right-6 bottom-8 h-28 w-28 rounded-full bg-red-600/20 blur-3xl" /><div className="relative rounded-[32px] border border-white/10 bg-slate-950/80 p-5 shadow-2xl shadow-black/40 backdrop-blur-xl"><div className="rounded-[28px] border border-white/10 bg-[linear-gradient(180deg,rgba(15,23,42,0.96),rgba(2,6,23,1))] p-6"><div className="flex items-center justify-between"><div><div className="text-sm uppercase tracking-[0.18em] text-slate-400">Live Queue Status</div><div className="mt-2 text-2xl font-black uppercase">NA Premier 5v5</div></div><div className="rounded-full border border-emerald-400/20 bg-emerald-500/10 px-3 py-1 text-sm font-bold text-emerald-300">Queue Open</div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><div className="text-sm text-slate-400">Trust Pool</div><div className="mt-2 text-3xl font-black text-blue-400">97.4%</div><div className="mt-2 text-sm text-slate-300">Verified players currently eligible for ranked entry.</div></div><div className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><div className="text-sm text-slate-400">Average Queue</div><div className="mt-2 text-3xl font-black text-red-400">01:42</div><div className="mt-2 text-sm text-slate-300">Fast matchmaking with integrity-gated sessions.</div></div></div><div className="mt-5 rounded-2xl border border-white/10 bg-white/[0.03] p-4"><div className="mb-3 flex items-center justify-between"><div className="text-sm uppercase tracking-[0.18em] text-slate-400">Enforcement Snapshot</div><div className="text-sm font-bold">Last 24h</div></div><div className="space-y-3">{[["Blocked sessions","184"],["Manual reviews","31"],["Shadow queue actions","14"]].map(([label,value]) => <div key={label} className="flex items-center justify-between rounded-xl border border-white/10 bg-slate-900/70 px-4 py-3"><span className="text-sm text-slate-300">{label}</span><span className="text-lg font-black">{value}</span></div>)}</div></div></div></div></div>
          </div>
        </div>
      </section>
      <section id="features" className="px-6 py-16 lg:px-10"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><div className="text-sm font-bold uppercase tracking-[0.22em] text-blue-300">Core Features</div><h2 className="mt-3 text-3xl font-black uppercase tracking-tight sm:text-4xl">Built for players who want real competition.</h2><p className="mt-4 text-slate-300">GamersOnline is positioned as a full competitive ecosystem: onboarding, ranked queues, anti-cheat operations, tournaments, and premium player tools.</p></div><div className="mt-10 grid gap-6 lg:grid-cols-3">{featureCards.map((card) => <div key={card.title} className={`rounded-[28px] border border-white/10 bg-gradient-to-br ${card.accent} p-6 shadow-xl shadow-black/20`}><div className="text-lg font-black uppercase tracking-wide">{card.title}</div><p className="mt-4 text-sm leading-7 text-slate-200">{card.desc}</p></div>)}</div></div></section>
      <section id="anti-cheat" className="border-y border-white/10 bg-white/[0.03] px-6 py-16 lg:px-10"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[1.05fr,0.95fr]"><div className="rounded-[28px] border border-white/10 bg-slate-950/70 p-6"><div className="text-sm font-bold uppercase tracking-[0.22em] text-red-300">Anti-Cheat</div><h2 className="mt-3 text-3xl font-black uppercase tracking-tight">Integrity is the product.</h2><p className="mt-4 max-w-2xl text-slate-300">GamersOnline is not just a queue website. The platform is designed around session validation, trust scoring, suspicious activity review, and controlled enforcement actions.</p><div className="mt-6 grid gap-4 sm:grid-cols-2">{["Launcher-based access gating","Device and session trust controls","Manual evidence review workflows","Shadow queue and block actions"].map((item) => <div key={item} className="rounded-2xl border border-white/10 bg-white/[0.03] p-4 text-sm text-slate-200">{item}</div>)}</div></div><div className="rounded-[28px] border border-red-400/15 bg-[linear-gradient(180deg,rgba(127,29,29,0.22),rgba(2,6,23,0.96))] p-6"><div className="text-sm font-bold uppercase tracking-[0.22em] text-red-200">Enforcement Queue</div><div className="mt-4 space-y-3">{[["Memory signature mismatch","High"],["Input anomaly cluster","Medium"],["Driver integrity failure","Critical"]].map(([signal,severity]) => <div key={signal} className="rounded-2xl border border-white/10 bg-black/20 p-4"><div className="text-sm text-slate-400">Flag Signal</div><div className="mt-1 font-semibold">{signal}</div><div className="mt-2 text-sm text-red-300">Severity: {severity}</div></div>)}</div></div></div></section>
      <section id="ladders" className="px-6 py-16 lg:px-10"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-2"><div className="rounded-[28px] border border-white/10 bg-slate-950/70 p-6"><div className="text-sm font-bold uppercase tracking-[0.22em] text-blue-300">Ranked Ladders</div><h2 className="mt-3 text-3xl font-black uppercase tracking-tight">Leaderboards that feel earned.</h2><div className="mt-6 space-y-3">{ladderRows.map((row) => <div key={row.place} className="grid gap-3 rounded-2xl border border-white/10 bg-white/[0.03] p-4 md:grid-cols-4"><div><div className="text-sm text-slate-400">Place</div><div className="text-xl font-black">{row.place}</div></div><div><div className="text-sm text-slate-400">Team</div><div className="font-semibold">{row.team}</div></div><div><div className="text-sm text-slate-400">ELO</div><div className="font-semibold">{row.elo}</div></div><div><div className="text-sm text-slate-400">Record</div><div className="font-semibold">{row.record}</div></div></div>)}</div></div><div className="rounded-[28px] border border-white/10 bg-slate-950/70 p-6"><div className="text-sm font-bold uppercase tracking-[0.22em] text-red-300">Tournament Hub</div><h2 className="mt-3 text-3xl font-black uppercase tracking-tight">Play leagues, cups, and qualifiers.</h2><div className="mt-6 space-y-3">{tournaments.map((event) => <div key={event.title} className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div className="font-semibold">{event.title}</div><div className="rounded-full bg-blue-500/10 px-3 py-1 text-xs font-bold uppercase tracking-wide text-blue-300">{event.status}</div></div><div className="mt-2 text-sm text-slate-300">{event.detail}</div></div>)}</div></div></div></section>
      <section id="pricing" className="border-t border-white/10 px-6 py-16 lg:px-10"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><div className="text-sm font-bold uppercase tracking-[0.22em] text-white/70">Pricing</div><h2 className="mt-3 text-3xl font-black uppercase tracking-tight">Start free. Upgrade when you grind harder.</h2></div><div className="mt-10 grid gap-6 lg:grid-cols-3">{pricing.map((plan) => <div key={plan.name} className={`rounded-[30px] border p-6 ${plan.featured ? "border-blue-400/30 bg-[linear-gradient(180deg,rgba(11,60,145,0.25),rgba(2,6,23,0.96))] shadow-2xl shadow-blue-950/30" : "border-white/10 bg-slate-950/70"}`}><div className="flex items-center justify-between"><div className="text-xl font-black uppercase">{plan.name}</div>{plan.featured ? <div className="rounded-full bg-red-500/10 px-3 py-1 text-xs font-bold uppercase tracking-wide text-red-200">Most Popular</div> : null}</div><div className="mt-4 text-4xl font-black">{plan.price}</div><div className="mt-6 space-y-3">{plan.features.map((feature) => <div key={feature} className="rounded-xl border border-white/10 bg-white/[0.03] px-4 py-3 text-sm text-slate-200">{feature}</div>)}</div><Link href="/billing" className={`mt-6 block w-full rounded-2xl px-4 py-3 text-center text-sm font-bold uppercase tracking-wide ${plan.featured ? "bg-brandRed text-white" : "bg-brandBlue text-white"}`}>Choose {plan.name}</Link></div>)}</div></div></section>
      <footer className="border-t border-white/10 bg-black/20 px-6 py-8 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="text-xl font-black uppercase tracking-wide">GamersOnline.gg</div><div className="mt-1 text-sm text-slate-400">Competitive CS2 platform for verified players and clean matches.</div></div><div className="flex flex-wrap gap-4 text-sm text-slate-300"><a href="#features">Features</a><a href="#ladders">Leaderboards</a><a href="#pricing">Pricing</a><Link href="/login">Login</Link></div></div></footer>
    </main>
  );
}
